# Generated by Django 2.2 on 2020-10-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(upload_to='')),
                ('license', models.TextField()),
                ('genre1', models.CharField(choices=[('Cl', 'Club'), ('DS', 'Dirty South'), ('EC', 'East Coast'), ('G', 'Gangsta'), ('P', 'Pop'), ('RB', 'R&B'), ('RG', 'Reggaeton'), ('U', 'Underground'), ('Ur', 'Urbam'), ('WC', 'West Coast')], max_length=2)),
                ('genre2', models.CharField(choices=[('Cl', 'Club'), ('DS', 'Dirty South'), ('EC', 'East Coast'), ('G', 'Gangsta'), ('P', 'Pop'), ('RB', 'R&B'), ('RG', 'Reggaeton'), ('U', 'Underground'), ('Ur', 'Urbam'), ('WC', 'West Coast')], max_length=2)),
                ('mood1', models.CharField(choices=[('A', 'Angry'), ('D', 'Dark'), ('E', 'Epic'), ('F', 'Frantic'), ('H', 'Happy'), ('I', 'Inspiring'), ('R', 'Relaxed'), ('S', 'Sad'), ('Si', 'Silly'), ('So', 'Soulful')], max_length=2)),
                ('mood2', models.CharField(choices=[('A', 'Angry'), ('D', 'Dark'), ('E', 'Epic'), ('F', 'Frantic'), ('H', 'Happy'), ('I', 'Inspiring'), ('R', 'Relaxed'), ('S', 'Sad'), ('Si', 'Silly'), ('So', 'Soulful')], max_length=2)),
                ('price', models.FloatField()),
                ('rate', models.CharField(max_length=5)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
