# Generated by Django 2.2 on 2020-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beatstoreuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeatStoreUser',
        ),
    ]
