# Generated by Django 2.2.4 on 2020-10-05 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201004_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
