# Generated by Django 2.2.4 on 2020-10-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_beat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='beat_name',
            field=models.CharField(default='cera', max_length=40),
            preserve_default=False,
        ),
    ]
