# Generated by Django 2.2.4 on 2020-10-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_beat_beat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Beat')),
            ],
        ),
    ]
