# Generated by Django 2.2 on 2020-10-07 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201005_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='beat_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=33),
            preserve_default=False,
        ),
    ]
