# Generated by Django 2.2 on 2020-10-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_beat_beat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='beat_id',
            field=models.CharField(max_length=33, unique=True),
        ),
    ]
