# Generated by Django 2.2 on 2020-10-07 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201007_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='sound_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
