# Generated by Django 2.2 on 2020-10-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_beat_sound_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='sound_two',
        ),
        migrations.CreateModel(
            name='BeatAgain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_two', models.FileField(upload_to='')),
                ('beat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Beat')),
            ],
        ),
    ]
