# Generated by Django 2.2 on 2020-10-08 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201007_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatagain',
            name='beat_name_again',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
