# Generated by Django 2.2 on 2020-10-08 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_beatagain_beat_name_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='sound_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BeatAgain',
        ),
    ]
