# Generated by Django 2.2 on 2020-10-10 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_sellerspays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellersPays',
            new_name='SellersPay',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Beat')),
            ],
        ),
    ]
