# Generated by Django 2.2 on 2020-10-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201013_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre1',
            field=models.CharField(choices=[('Cl', 'Club'), ('DS', 'Dirty South'), ('EC', 'East Coast'), ('G', 'Gangsta'), ('P', 'Pop'), ('RB', 'R&B'), ('RG', 'Reggaeton'), ('U', 'Underground'), ('Ur', 'Urban'), ('WC', 'West Coast')], max_length=2),
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre2',
            field=models.CharField(choices=[('Cl', 'Club'), ('DS', 'Dirty South'), ('EC', 'East Coast'), ('G', 'Gangsta'), ('P', 'Pop'), ('RB', 'R&B'), ('RG', 'Reggaeton'), ('U', 'Underground'), ('Ur', 'Urban'), ('WC', 'West Coast')], max_length=2),
        ),
    ]
