# Generated by Django 2.2 on 2020-10-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201019_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('account_number', models.CharField(max_length=15)),
            ],
        ),
    ]
