# Generated by Django 2.2 on 2020-10-22 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='genre2',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile-pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre1',
            field=models.CharField(choices=[('Cl', 'Club'), ('P', 'Pop'), ('RG', 'Reggaeton'), ('U', 'Underground'), ('A', 'Afro'), ('AP', 'Afro Pop'), ('AR', 'Afro Reggae'), ('R&B', 'Afro R&B'), ('AB', 'Afro Blues'), ('B', 'Bangare')], max_length=2),
        ),
    ]
