# Generated by Django 2.2 on 2020-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201022_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='genre1',
            field=models.CharField(choices=[('Cl', 'Club'), ('P', 'Pop'), ('RG', 'Reggaeton'), ('U', 'Underground'), ('A', 'Afro'), ('AP', 'Afro Pop'), ('AR', 'Afro Reggae'), ('R&B', 'Afro R&B'), ('AB', 'Afro Blues'), ('B', 'Bangare')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('m', 'Musician'), ('p', 'Producer'), ('ma', 'Manager'), ('pro', 'PRO'), ('co', 'Compose'), ('sw', 'Songwriter'), ('lb', 'Label brand & Sponsor'), ('di', 'Director'), ('mo', 'Model'), ('pa', 'Painter'), ('st', 'Stylist'), ('ac', 'Actor'), ('me', 'Media'), ('de', 'Designer'), ('pg', 'Photographer'), ('pt', 'Poet'), ('bd', 'Band'), ('tc', 'Teacher'), ('dc', 'Dancer'), ('cm', 'Comedian'), ('so', 'Show Organizers')], max_length=4),
        ),
    ]
