# Generated by Django 2.2 on 2020-10-23 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ordercontactprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprof',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
