# Generated by Django 2.2 on 2020-10-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contactprof_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
    ]
