# Generated by Django 2.2 on 2020-10-23 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_profile_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('m', 'Musician'), ('p', 'Producer'), ('ma', 'Manager'), ('pro', 'PRO'), ('co', 'Compose'), ('sw', 'Songwriter'), ('lb', 'Label brand & Sponsor'), ('di', 'Director'), ('mo', 'Model'), ('pa', 'Painter'), ('st', 'Stylist'), ('ac', 'Actor'), ('me', 'Media'), ('de', 'Designer'), ('pg', 'Photographer'), ('pt', 'Poet'), ('bd', 'Band'), ('tc', 'Teacher'), ('dc', 'Dancer'), ('cm', 'Comedian'), ('so', 'Show Organizers')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
