# Generated by Django 2.2 on 2020-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_contactcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='producer_name',
            field=models.CharField(default='new user', max_length=45),
            preserve_default=False,
        ),
    ]
