# Generated by Django 2.2 on 2020-11-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_beat_producer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='mood2',
        ),
    ]
