# Generated by Django 2.2 on 2020-11-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_beat_mood2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='beat_id',
        ),
    ]
